services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    # Make sure your app knows where to find the app factory / module if needed:
    environment:
      FLASK_APP: run_planner/wsgi.py   # or "your_module:app"

   db:
    image: postgres:16
    environment:
      POSTGRES_USER: runplanner
      POSTGRES_PASSWORD: runplanner
      POSTGRES_DB: runplanner
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U runplanner -d runplanner"]
      interval: 2s
      timeout: 3s
      retries: 15


